# Generated by Django 2.2.15 on 2020-08-10 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_auto_20200810_0541"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customtext_test",
                to="home.HomePage",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="demo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homepage_demo",
                to="home.CustomText",
            ),
        ),
    ]
