# Generated by Django 2.2.15 on 2020-08-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200810_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='test',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='titleChanged',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body123',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='demo',
        ),
        migrations.AddField(
            model_name='customtext',
            name='hvghgjgjhgfhjg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='nfghgfhgf',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='jhgfhjgjhgjhg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
